name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use latest Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'node' # This ensures latest available Node is used

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
